name: ColoredEnderChests
version: ${project.version}
author: TheBusyBiscuit
website: https://github.com/TheBusyBiscuit/ColoredEnderChests

main: io.github.thebusybiscuit.coloredenderchests.ColoredEnderChests
api-version: 1.13

depend: 
- Slimefun

softdepend:
  - GuizhanLibPlugin